# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Backend-Integrity

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install with Maven
        run: cd wbs/alarm/ && mvn install --file pom.xml
      - name: Build with Maven
        run: cd wbs/alarm/ && mvn -B package --file pom.xml
