# This will be displayed in every PR
name: Compare to base

# This will control when the action will be run. In this case the action will be run on every PR
on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-integrity:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Do a clean install on unix
      - name: Clean install
        run: cd wbs-alarm/wbs-frontend/ && npm run reinstall_ux

      # Do a run of the automated tests
      - name: Run tests
        run: cd wbs-alarm/wbs-frontend/ && npm run test-headless

      # Do a test build
      - name: Run build
        run: cd wbs-alarm/wbs-frontend/ && npm run build
